### ISSUE TITLE
implement bitmex_candles please

### ISSUE THREAD

**Issue by materemias** [libcryptomarket/libcryptomarket#24]
bitmex bucketed trades would be awesome, if there are no other requests please implement it next.

**Comment by materemias** [comment]
#25

**Comment by gavincyi** [comment]
Cool thanks for your contribution!
Actually now the usage is a bit changed and your code change will be migrated to `inject.py`, so the users can fetch the candles by , for example, 

```
from libcryptomarket import bitmex

candles = bitmex.fetch_candles(symbol="XBT/USD", frequency="30m", ...)
```

I will remove the `exchange.py` after the migration. 

You code change is wonderful. :)
