### ISSUE TITLE
Order Book Data

### ISSUE THREAD

**Issue by akaniklaus** [libcryptomarket/libcryptomarket#6]
Hello!

As there is no database of order book movements (in conjunction with order history) for crypto currencies, as opposed to some traditional markets such as NYSE, I would like to urge owners of this repository to extend their work with it. With the recent advancement in Deep Reinforcement Learning, I strongly believe that this data would be valuable for lots of future research in this field.

Thank you very much for your consideration. Here is a related presentation from JP Morgan Stanley, which you can check about this topic: https://www.slideshare.net/Quantopian/active-learning-in-trading-algorithms-by-david-fellah-head-of-the-emea-linear-quant-research-group-at-jp-morgan

Sincerely,
Kamer

**Comment by gavincyi** [comment]
Understood thanks.
